version: '3.4'

services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lite-api
    expose:
      - 5432
    ports:
      - 5462:5432
    networks:
      - lite

  api:
    env_file:
      - .env
    build: .
    volumes:
      - .:/app
    ports:
      - 8100:8100
    links:
      - db
    expose:
      - 8100
    command: ./manage.py runserver 0.0.0.0:${PORT:-8100}
    networks:
      - lite

networks:
  lite:
    external: true
